### ISSUE TITLE
Steps to join Ethereum Reaserch foundation

### ISSUE THREAD

**Issue by aj07** [ethereum/research#79]
I want to be part of ETH research foundation for one topic on pure research and applied research.

Please , let me know or point me any  docs to get started.

**Comment by ChihChengLiang** [comment]
hi @aj07 , try this https://ethresear.ch/

**Comment by aj07** [comment]
hello @ChihChengLiang  I also raised discussion there. but no luck

**Comment by aj07** [comment]
Close
